// genshim 把 Wails 自动生成的 frontend/wailsjs/go/main/App.js 转换为 HTTP 桩：
// 每个 export function 的函数体由
//
//	return window['go']['main']['App']['Name'](arg1, arg2);
//
// 改为
//
//	return rpc("Name", [arg1, arg2]);
//
// 并在文件顶部注入 import { rpc } from transport。可重复执行：已是 rpc 的行不受影响，
// 因此后续 Wails 重新生成绑定后再次运行本工具即可刷新桩。用法：go run ./server/cmd/genshim
package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

func main() {
	path := "frontend/wailsjs/go/main/App.js"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}

	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, "读取失败:", err)
		os.Exit(1)
	}
	src := string(data)

	// 匹配 window['go']['main']['App']['NAME'](args)；args 为简单标识符列表（不含括号）。
	re := regexp.MustCompile(`window\['go'\]\['main'\]\['App'\]\['(\w+)'\]\(([^)]*)\)`)
	out := re.ReplaceAllString(src, `rpc("$1", [$2])`)

	out = strings.Replace(out,
		"// This file is automatically generated. DO NOT EDIT",
		"// HTTP 桩：由 server/cmd/genshim 从 Wails 绑定转换而来（可重复执行；勿手改）",
		1)

	const imp = "import { rpc } from \"../../../src/api/transport.js\";"
	if !strings.Contains(out, imp) {
		nl := strings.Index(out, "\n")
		if nl < 0 {
			nl = 0
		}
		out = out[:nl+1] + imp + "\n" + out[nl+1:]
	}

	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "写入失败:", err)
		os.Exit(1)
	}
	fmt.Println("genshim: 已转换", path)
}
